src/blueprints/votacao/models.py
import datetime

from ext.database import db


candidatos_eleicao = db.Table('candidatos_eleicao',
    db.Column('id', db.Integer, primary_key=True),
    db.Column('candidato_id', db.Integer, db.ForeignKey('candidato.id')),
    db.Column('eleicao_id', db.Integer, db.ForeignKey('eleicao.id')),
    db.Column('total_votos', db.Integer)
)

class Candidato(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(150), unique=True, nullable=False)

    def __repr__(self):
        return '<Candidato %r>' % self.nome
    

class Eleicao(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    descricao = db.Column(db.String(100), unique=True, nullable=False)
    status = db.Column(db.Boolean, default=False, nullable=False)
    datahora = db.Column(db.DateTime, default=datetime.datetime.now, nullable=False)
    candidatos = db.relationship('Candidato', secondary=candidatos_eleicao, lazy='subquery',
        backref=db.backref('eleicoes', lazy=True))

    def __repr__(self):
        return '<Eleicao %r>' % self.id
    

class VotoEleicao(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    datahora = db.Column(db.DateTime, nullable=False)
    ip = db.Column(db.String(150), nullable=False)
    hash = db.Column(db.String(150), unique=True, nullable=False)
    candidato_eleicao_id = db.Column(db.Integer, db.ForeignKey('candidatos_eleicao.id')) 

    def __repr__(self):
        return '<VotoEleicao %r>' % self.id

    

src/app.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret-key'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///teste.sqlite3'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = True
    app.config['CACHE_TYPE'] = "SimpleCache"
    app.config['CACHE_DEFAULT_TIMEOUT'] = 300

    with app.app_context():
        from ext.database import db
        from ext.cache import cache

        db.init_app(app)
        cache.init_app(app)

        from blueprints.votacao import bp_votacao
        app.register_blueprint(bp_votacao, url_prefix='/')
    
    return app


if __name__ == '__main__':    
    app = create_app()

    app.run(
        port=5000,
        debug=True
    )

src/blueprints/votacao/__init__.py
from flask import Blueprint

bp_votacao = Blueprint('votacao', __name__)


from blueprints.votacao import routes

src/blueprints/votacao/routes.py
import datetime

from flask import request, render_template, redirect, flash, url_for

from ext.cache import cache
from ext.pika_connection import create_pika_connection

from blueprints.votacao.doa import EleicaoCrud, CandidatoCRUD, VotoEleicaoCRUD

from blueprints.votacao import bp_votacao


@bp_votacao.before_app_first_request
def update_status_eleicao():
    eleicao = EleicaoCrud.get_eleicao_ativa()
    
    if eleicao.status:
        cache.set('eleicao_ativa', True)

@bp_votacao.route('/', methods=['GET'])
@cache.cached(timeout=10)
def index():
    resultado_eleicao = VotoEleicaoCRUD.resultado_eleicao()
    return render_template('index.html', resultado_eleicao=resultado_eleicao)

@bp_votacao.route('/eleicao/novo', methods=['GET','POST'])
def eleicao_novo():
    if request.method == 'POST':
        try:
            eleicao = EleicaoCrud.save_eleicao(
                request.form
            )

            if eleicao.status:
                cache.set('eleicao_ativa', True)

            flash('Eleição criada!', 'success')
            return redirect('/eleicoes')
        except Exception as e:
            flash(str(e), 'danger')
            return redirect(url_for('votacao.eleicao_novo'))

    return render_template('form_eleicao.html')

@bp_votacao.route('/eleicoes', methods=['GET'])
def eleicoes():
    eleicoes = EleicaoCrud.all_eleicoes()
    return render_template('eleicoes.html', eleicoes=eleicoes)

@bp_votacao.route('/eleicao/deletar', methods=['POST'])
def eleicao_deletar():
    EleicaoCrud.delete_eleicao(request.form['id'])
    flash('Removido com sucesso!', 'success')
    return redirect('/eleicoes')

@bp_votacao.route('/candidato/novo', methods=['GET','POST'])
def candidato_novo():
    if request.method == 'POST':
        try:
            CandidatoCRUD.save_candidato(
                request.form
            )
            flash('Candidato criado!', 'success')
            return redirect('/candidatos')
        except Exception as e:
            flash(str(e), 'danger')
            return redirect(url_for('votacao.candidato_novo'))

    return render_template('form_candidato.html')

@bp_votacao.route('/candidatos', methods=['GET'])
def candidatos():
    candidatos = CandidatoCRUD.all_candidatos()
    return render_template('candidatos.html', candidatos=candidatos)

@bp_votacao.route('/candidato/deletar', methods=['POST'])
def candidato_deletar():
    try:
        CandidatoCRUD.delete_candidato(request.form['id'])
        flash('Removido com sucesso!', 'success')
        return redirect('/candidatos')
    except Exception as e:
        flash(str(e), 'danger')
        return redirect('/candidatos')


@bp_votacao.route('/eleicao/<id_eleicao>/candidatos', methods=['GET'])
def eleicao_candidatos(id_eleicao):
    candidaturas = EleicaoCrud.get_candidatos_eleicao(id_eleicao)
    return render_template('candidatos_eleicao.html', candidaturas=candidaturas, id_eleicao=id_eleicao)

@bp_votacao.route('/eleicao/<id_eleicao>/candidato/novo', methods=['POST','GET'])
def eleicao_candidato_novo(id_eleicao):
    if request.method == 'POST':
        try:
            EleicaoCrud.save_candidato_eleicao(
                id_eleicao, request.form
            )
            flash('Candidato vinculado a eleição!', 'success')
            return redirect(url_for('votacao.eleicao_candidatos', id_eleicao=id_eleicao))
        except Exception as e:
            flash(str(e), 'danger')
            return redirect(url_for('votacao.eleicao_candidato_novo', id_eleicao=id_eleicao))
        
    candidatos = CandidatoCRUD.all_candidatos()

    return render_template('form_eleicao_candidato.html', candidatos=candidatos, id_eleicao=id_eleicao)


@bp_votacao.route('/eleicao/<id_eleicao>/candidato/deletar', methods=['POST'])
def candidato_eleicao_deletar(id_eleicao):
    try:
        EleicaoCrud.delete_candidato_eleicao(id_eleicao, request.form['id'])
        flash('Removido com sucesso!', 'success')
        return redirect(url_for('votacao.eleicao_candidatos', id_eleicao=id_eleicao))
    except Exception as e:
        flash(str(e), 'danger')
        return redirect(url_for('votacao.eleicao_candidatos', id_eleicao=id_eleicao))

@bp_votacao.route('/eleicao/altera_status', methods=['POST'])
def change_status_eleicao():
    try:
        id_eleicao = request.form['id_eleicao']
        eleicao = EleicaoCrud.change_status_eleicao(id_eleicao)

        if eleicao.status == False:
            cache.set('eleicao_ativa', False)
        else:
            cache.set('eleicao_ativa', True)

        return redirect('/eleicoes')
    except Exception as e:
        flash(str(e), 'danger')
        return redirect('/eleicoes')
    
@bp_votacao.route('/votar', methods=['GET','POST'])
def votar():
    eleicao_ativa = cache.get('eleicao_ativa')

    if not eleicao_ativa:
        flash('Nenhuma eleição ativa!', 'danger')
        return redirect('/')

    if request.method == 'POST':
        try:
            dados = {}
            dados['candidato_eleicao_id'] = int(request.form['candidato_eleicao_id'])
            dados['datahora'] = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S,%f")
            dados['ip'] = request.remote_addr

            dados_to_string = str(dados)

            # cria conexao, declara e manda dados a fila
            connection = create_pika_connection()
            channel = connection.channel()
            channel.queue_declare(queue='exemplo_fila')

            channel.basic_publish(exchange='', routing_key='exemplo_fila', body=dados_to_string)
            connection.close()

            flash('Voto salvo!', 'success')
            return redirect('/')
        except Exception as e:
            flash(str(e), 'danger')
            return redirect(url_for('votacao.votar'))

    eleicao_candidatos = VotoEleicaoCRUD.candidatos_eleicao()
    return render_template('votar.html', eleicao_candidatos=eleicao_candidatos)

src/templates/_messages.html
<div class="block">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul>
        {% for category, message in messages %}
          <li class="notification is-{{ category }}">{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    </div>

src/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Votação</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-info is-fullheight" style="display: block;">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('votacao.index') }}" class="navbar-item">
                                Home
                            </a>
                            <a href="{{ url_for('votacao.eleicoes') }}" class="navbar-item">
                                Eleição
                            </a>
                            <a href="{{ url_for('votacao.candidatos') }}" class="navbar-item">
                                Candidatos
                            </a>
                            <a href="{{ url_for('votacao.votar') }}" class="navbar-item">
                                Votar
                            </a>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">

            <div class="container has-text-centered">
                {% include '_messages.html'%}

                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

src/templates/candidatos.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
    Candidatos
</h1>

<div class="buttons">
  <a href="{{ url_for('votacao.candidato_novo') }}" class="button is-light" >Novo</a>
  </div>


{% if candidatos %}

<table class="table is-fullwidth">
    <thead>
      <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Deletar</th>
      </tr>
    </thead>
    <tbody>
    {% for candidato in candidatos %}
    <tr>
        <th>{{ candidato.id }}</th>
        <td>{{ candidato.nome }}</td>
        <td>
            <form action="{{ url_for('votacao.candidato_deletar') }}" method="post" >
              <input name="id" type="hidden" value="{{ candidato.id }}">
              <button class="button is-danger" type="submit">Deletar</button>
          </form>
          </td>    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endif %}

{% endblock %}

src/templates/candidatos_eleicao.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
    Candidatos eleição
</h1>

{% if candidaturas %}

<div class="buttons">
  <a href="{{ url_for('votacao.eleicao_candidato_novo', id_eleicao=id_eleicao) }}" class="button is-light" >Novo</a>
  </div>
  

<table class="table is-fullwidth ">
    <thead>
      <tr>
        <th>ID</th>
        <th>Candidato</th>
        <th>Deletar</th>
      </tr>
    </thead>
    <tbody>
    {% for candidatura in candidaturas %}
    <tr>
        <th>{{ candidatura.id }}</th>
        <td>{{ candidatura.nome }}</td>
        <td class="buttons">
          <form action="{{ url_for('votacao.candidato_eleicao_deletar', id_eleicao=id_eleicao) }}" method="post" >
            <input name="id" type="hidden" value="{{ candidatura.id }}">
            <button class="button is-danger" type="submit">Deletar</button>
          </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endif %}

{% endblock %}

src/templates/eleicoes.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
    Eleições
</h1>

<div class="buttons">
<a href="{{ url_for('votacao.eleicao_novo') }}" class="button is-light" >Novo</a>
</div>

{% if eleicoes %}

<table class="table is-fullwidth ">
    <thead>
      <tr>
        <th>ID</th>
        <th>Descrição</th>
        <th>Data hora</th>
        <th>Status</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
    {% for eleicao in eleicoes %}
    <tr>
        <th>{{ eleicao.id }}</th>
        <td>{{ eleicao.descricao }}</td>
        <td>{{ eleicao.datahora.strftime('%d/%m/%Y %H:%M:%S') }}</td>
        <td>{% if eleicao.status %} Ativo {% else %} Inativo {% endif %}</td>
        <td class="buttons">
          <a href="{{ url_for('votacao.eleicao_candidatos', id_eleicao=eleicao.id)}}" class="button is-link">Candidatos</a>
          <form action="{{ url_for('votacao.eleicao_deletar') }}" method="post" >
            <input name="id" type="hidden" value="{{ eleicao.id }}">
            <button class="button is-danger" type="submit">Deletar</button>
          </form>
          <form action="{{ url_for('votacao.change_status_eleicao') }}" method="post" >
            <input name="id_eleicao" type="hidden" value="{{ eleicao.id }}">
            <button class="button is-info" style="margin-left: 0.5rem;" type="submit">Alterar status</button>
          </form>
        </td>
    </tr>
    {% endfor %}
    </tbody>
  </table>

{% endif %}

{% endblock %}

src/templates/form_candidato.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Candidato</h3>
    <div class="box">
        <form method="POST" action="{{ url_for('votacao.candidato_novo') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="nome" placeholder="Nome" autofocus="">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/form_eleicao.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Eleição</h3>
    <div class="box">
        <form method="POST" action="{{ url_for('votacao.eleicao_novo') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="descricao" placeholder="Descrição" autofocus="">
                </div>
                <label class="checkbox">
                    <input type="checkbox" name="status" value="1" >
                    Ativo
                  </label>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/form_eleicao_candidato.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Candidato</h3>
    <div class="box">
        <form method="POST" action="{{ url_for('votacao.eleicao_candidato_novo', id_eleicao=id_eleicao) }}">
            <div class="field">
                <div class="control">
                    <div class="select">
                        <select name="candidato">
                           <option selected disabled > --- </option>
                          {% for candidato in candidatos %}
                            <option value="{{ candidato.id }}">{{  candidato.nome }}</option>
                          {% endfor %}
                        </select>
                      </div>
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Salvar</button>
        </form>
    </div>
</div>
{% endblock %}

src/templates/index.html
{% extends "base.html" %}

{% block content %}


<h1 class="title">
    Votação
</h1>

{% if resultado_eleicao%}
<div class="content">
    {% for candidato in resultado_eleicao.candidatos_eleicao %}
    <h2 class="subtitle">{{ candidato.nome }}</h2>   
    <progress class="progress is-success" value="{{ candidato.percentual }}" max="100">{{ candidato.total_votos }}%</progress>
    {% endfor %}
    <h2 class="title">Total de votos</h2>   
    <h2 class="subtitle">{{ resultado_eleicao.total_votos_eleicao }}</h2>
</div>
{% else %}
<h2 class="subtitle">Sem eleição ativa</h2>
{% endif %}






{% endblock %}

src/templates/votar.html
{% extends "base.html" %}

{% block content %}

<h1 class="title">
    Escolha uma candidato
</h1>

<div class="card">
    <div class="card-footer">
    {% for eleicao_candidato in eleicao_candidatos %}
    <form class="card-footer-item"action="{{url_for('votacao.votar')}}" method="POST">
        <a href="#" onclick="parentNode.submit()">{{ eleicao_candidato.nome }}</a>
        <input type="hidden" name="candidato_eleicao_id" value="{{ eleicao_candidato.id }}">
    </form>
    {% endfor %}
    </div>
</div>

{% endblock %}